# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2

from PyQt5 import QtCore, QtGui, QtWidgets
from ResNet50 import ResNet50

class Ui_MainWindow(object):

    def __init__(self):
        self.resNet50 = ResNet50()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 221, 461))
        self.groupBox.setObjectName("groupBox")

        self.loadImage = QtWidgets.QPushButton(self.groupBox)
        self.loadImage.setGeometry(QtCore.QRect(20, 30, 181, 41))
        self.loadImage.setObjectName("loadImage")
        self.loadImage.clicked.connect(self.LoadImageClicked)

        self.showImages = QtWidgets.QPushButton(self.groupBox)
        self.showImages.setGeometry(QtCore.QRect(20, 100, 181, 41))
        self.showImages.setObjectName("showImages")
        self.showImages.clicked.connect(self.ShowImagesClicked)

        self.showDistribution = QtWidgets.QPushButton(self.groupBox)
        self.showDistribution.setGeometry(QtCore.QRect(20, 170, 181, 41))
        self.showDistribution.setObjectName("showDistribution")
        self.showDistribution.clicked.connect(self.ShowDistributionClicked)

        self.showModelStructure = QtWidgets.QPushButton(self.groupBox)
        self.showModelStructure.setGeometry(QtCore.QRect(20, 240, 181, 41))
        self.showModelStructure.setObjectName("showModelStructure")
        self.showModelStructure.clicked.connect(self.ShowModelStructureClicked)

        self.showComparison = QtWidgets.QPushButton(self.groupBox)
        self.showComparison.setGeometry(QtCore.QRect(20, 310, 181, 41))
        self.showComparison.setObjectName("showComparison")
        self.showComparison.clicked.connect(self.ShowComparisonClicked)

        self.Inference = QtWidgets.QPushButton(self.groupBox)
        self.Inference.setGeometry(QtCore.QRect(20, 380, 181, 41))
        self.Inference.setObjectName("Inference")
        self.Inference.clicked.connect(self.InferenceClicked)

        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(360, 70, 331, 331))
        self.screen.setText("")
        self.screen.setObjectName("screen")

        self.txt = QtWidgets.QLabel(self.centralwidget)
        self.txt.setGeometry(QtCore.QRect(360, 300, 200, 200))
        self.txt.setObjectName("txt")
        self.txt.setStyleSheet('font-size:18px;')

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "5. ResNet50"))
        self.loadImage.setText(_translate("MainWindow", "Load Image"))
        self.showImages.setText(_translate("MainWindow", "1 .Show Images"))
        self.showDistribution.setText(_translate("MainWindow", "2. Show Distribution"))
        self.showModelStructure.setText(_translate("MainWindow", "3. Show Model Structure"))
        self.showComparison.setText(_translate("MainWindow", "4. Show Comparison"))
        self.Inference.setText(_translate("MainWindow", "5. Inference"))

    def LoadImageClicked(self):

        # at home
        '''train = QtWidgets.QFileDialog.getExistingDirectory(None, "Load folder", "./")
        valid = QtWidgets.QFileDialog.getExistingDirectory(None, "Load folder", "./")
        self.resNet50.LoadImage(train, valid)'''

        # demo
        fileName = QtWidgets.QFileDialog.getOpenFileName(None, 'OpenFile', './')

        if fileName != ('',''):
            img = cv2.imread(fileName[0])
            img = cv2.resize(img,(224,224))
            cv2.imwrite('ResizeInferenceImg.jpg', img)

            pix = QtGui.QPixmap('ResizeInferenceImg.jpg')
            self.screen.setPixmap(pix)

            self.resNet50.LoadImage('ResizeInferenceImg.jpg')

    def ShowImagesClicked(self):
        self.resNet50.ShowImages()

    def ShowDistributionClicked(self):
        self.resNet50.ShowDistribution()

    def ShowModelStructureClicked(self):
        self.resNet50.ShowModelStructure()

    def ShowComparisonClicked(self):
        self.resNet50.ShowComparison()

    def InferenceClicked(self):
        c = self.resNet50.Inference()
        if c != '':
            self.txt.setText('Prediction: ' + c)